spring.application.name = journalApp
spring.mongodb.uri = mongodb+srv://yuvrajsingh:20041920%40abc@cluster0.rtmu6uh.mongodb.net/journaldb
spring.data.mongodb.auto-index-creation=true

#used when we have authentication in our app
#spring.mongodb.username = myjournaluser
#spring.mongodb.password = mypassword