spring.application.name = journalApp
spring.mongodb.host = localhost
spring.mongodb.port = 27017
spring.mongodb.database = journaldb

#used when we have authentication in our app
#spring.mongodb.username = myjournaluser
#spring.mongodb.password = mypassword